theme: jekyll-theme-minimal

title: Nấm lùn mặc đẹp

description: Nấm lùn mặc đẹp

name: Nấm lùn mặc đẹp

email: dotrananhduc117@gmail.com

baseurl: ""

url: "https://www.namlunmacdep.com"

google_analytics: UA-195355610-1

encoding: UTF-8

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: 
  instagram:
  linkedin:
  pinterest:
  rss: 
  twitter: jekyllrb
  stackoverflow: 
  youtube: 
  googleplus: # anything in your profile username that comes after plus.google.com/

include: ['_pages']

timezone: Asia/Ho_Chi_Minh

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

collections:
  pagehackdang:
    output: true
    permalink: /hack-dang/:title
  pagephoido:
    output: true
    permalink: /phoi-do/:title
  pagebodytype:
    output: true
    permalink: /body-type/:title
  pagemactheodip:
    output: true
    permalink: /mac-theo-dip/:title
  pagemactheostyle:
    output: true
    permalink: /mac-theo-style/:title
  pagechupanh:
    output: true
    permalink: /chup-anh/:title
  pageclub:
    output: true
    permalink: /club1m5/:title

plugin:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

paginate: 5
paginate_path: "/page:num/"
permalink: /:title/